const STORAGE_KEY = 'kousakuReservations';
const slots = { 1: { meet: '10:50', experience: '11:00〜12:00' }, 2: { meet: '12:50', experience: '13:00〜14:00' }, 3: { meet: '14:50', experience: '15:00〜16:00' } };
let draft = null;
const $ = (selector) => document.querySelector(selector);
const all = () => { try { const value = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); return Array.isArray(value) ? value : []; } catch (error) { console.error('予約データの読み込みに失敗しました', error); return []; } };
const save = (data) => localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
function show(id) { document.querySelectorAll('.screen').forEach((screen) => screen.classList.toggle('active', screen.id === id)); window.scrollTo({ top: 0, behavior: 'smooth' }); if (id === 'admin') renderAdmin(); }
function formatDate(value) { if (!value) return ''; const [year, month, day] = value.split('-'); return `${year}年${Number(month)}月${Number(day)}日`; }
function escapeHtml(value) { return String(value ?? '').replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character])); }
function renderConfirm() { const rows = [['予約日', formatDate(draft.date)], ['集合時間', draft.meet], ['体験時間', draft.experience], ['人数', `${draft.guests}名`], ['氏名', draft.name], ['年代', draft.age], ['初回 / リピーター', draft.visit], ['メールアドレス', draft.email], ['流入元', draft.source], ['備考', draft.note]]; $('#confirm-content').innerHTML = `<dl>${rows.map(([label, value]) => `<div class="summary-row"><dt>${label}</dt><dd>${escapeHtml(value)}</dd></div>`).join('')}</dl>`; }
function missingFields(form) { const labels = { date: '希望日', slot: '希望時間', guests: '人数', name: '氏名', email: 'メールアドレス', age: '年代', visit: '初回 / リピーター' }; return Object.entries(labels).filter(([name]) => !String(form.get(name) || '').trim()).map(([, label]) => label); }
$('#booking-form').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const missing = missingFields(form); if (missing.length) { alert(`以下の項目を入力してください：\n${missing.join('、')}`); return; } const slot = slots[form.get('slot')]; if (!slot) return alert('希望時間を選択してください。'); const selectedDate = new Date(`${form.get('date')}T00:00:00`); if ([1, 2, 3, 4, 5].includes(selectedDate.getDay())) return alert('香作ワークショップは土日祝日の開催です。開催日をご確認ください。'); draft = { date: form.get('date'), slot: form.get('slot'), meet: slot.meet, experience: slot.experience, guests: Number(form.get('guests')), name: form.get('name').trim(), email: form.get('email').trim(), age: form.get('age'), visit: form.get('visit'), source: form.get('source') || '未回答', note: form.get('note') || '未記入' }; renderConfirm(); show('confirm'); });
$('#confirm-button').addEventListener('click', () => { if (!draft) return; save([...all(), { ...draft, id: `KS-${Date.now().toString(36).toUpperCase()}`, status: '受付', createdAt: new Date().toISOString() }]); draft = null; $('#booking-form').reset(); show('complete'); });
function renderAdmin() { const data = all().sort((a, b) => `${a.date}${a.slot}`.localeCompare(`${b.date}${b.slot}`)); $('#reservation-count').textContent = `${data.length}件`; const first = data.filter((item) => item.visit === '初めて').length; const total = data.reduce((sum, item) => sum + Number(item.guests || 0), 0); const repeat = data.length - first; const bars = (values, key) => values.map((value) => { const count = data.filter((item) => item[key] === value).length; const max = Math.max(1, ...values.map((v) => data.filter((item) => item[key] === v).length)); return `<div class="bar-row"><span class="bar-label">${value}</span><span class="bar-track"><span class="bar-fill" style="width:${count / max * 100}%"></span></span><span>${count}</span></div>`; }).join(''); $('#metrics').innerHTML = `<div class="metric"><p>総予約件数</p><strong>${data.length}</strong><small>件</small></div><div class="metric"><p>総参加人数</p><strong>${total}</strong><small>名</small></div><div class="metric"><p>初回利用者数</p><strong>${first}</strong><small>件</small></div><div class="metric"><p>リピーター数</p><strong>${repeat}</strong><small>件</small></div><div class="metric metric-wide"><p>年代別予約数</p>${bars(['10代', '20代', '30代', '40代', '50代', '60代以上'], 'age')}</div><div class="metric metric-wide"><p>流入元別予約数</p>${bars(['Google検索', 'Instagram', '口コミ', '店頭', '知人の紹介', 'その他', '未回答'], 'source')}</div>`; $('#reservation-list').innerHTML = data.length ? data.map((item) => `<article class="reservation-item"><div class="reservation-main"><div class="reservation-date">${formatDate(item.date)}<div class="reservation-sub">${item.meet}集合</div></div><div class="reservation-name">${escapeHtml(item.name)}<div class="reservation-sub">${item.guests}名 / ${escapeHtml(item.age)} / ${escapeHtml(item.visit)} / ${escapeHtml(item.source)}</div></div><select class="status-select" data-status="${item.id}" aria-label="予約状況"><option ${item.status === '受付' ? 'selected' : ''}>受付</option><option ${item.status === '確認済み' ? 'selected' : ''}>確認済み</option><option ${item.status === 'キャンセル' ? 'selected' : ''}>キャンセル</option></select></div><button class="secondary-button small" data-detail="${item.id}">詳細を見る</button></article>`).join('') : '<p class="no-data">まだ予約データがありません。</p>'; }
document.addEventListener('click', (event) => { const button = event.target.closest('[data-screen]'); if (button) { event.preventDefault(); show(button.dataset.screen); } const detailId = event.target.dataset.detail; if (detailId) showDetail(all().find((item) => item.id === detailId)); if (event.target.closest('[data-close-detail]')) $('#detail-panel').hidden = true; });
document.addEventListener('change', (event) => { if (!event.target.dataset.status) return; const data = all(); const item = data.find((entry) => entry.id === event.target.dataset.status); if (item) { item.status = event.target.value; save(data); } });
function showDetail(item) { if (!item) return; $('#detail-panel').hidden = false; $('#detail-panel').innerHTML = `<button class="detail-close" data-close-detail>閉じる</button><h2>予約詳細</h2>${[['予約ID', item.id], ['予約日', formatDate(item.date)], ['集合時間', item.meet], ['体験時間', item.experience], ['人数', `${item.guests}名`], ['氏名', item.name], ['メール', item.email], ['年代', item.age], ['来店回数', item.visit], ['流入元', item.source], ['備考', item.note], ['作成日時', new Date(item.createdAt).toLocaleString('ja-JP')]].map(([label, value]) => `<div class="detail-row"><b>${label}</b>${escapeHtml(value)}</div>`).join('')}`; }
$('#date').min = new Date().toISOString().slice(0, 10);
