const STORAGE_KEY='kousakuReservations';
const slots={1:{meet:'10:50',experience:'11:00〜12:00'},2:{meet:'12:50',experience:'13:00〜14:00'},3:{meet:'14:50',experience:'15:00〜16:00'}};
let draft=null;
const $=s=>document.querySelector(s);
const all=()=>{try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]')}catch{return[]}};
function save(data){localStorage.setItem(STORAGE_KEY,JSON.stringify(data))}
function show(id){document.querySelectorAll('.screen').forEach(el=>el.classList.toggle('active',el.id===id));window.scrollTo({top:0,behavior:'smooth'});if(id==='admin')renderAdmin()}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-screen]');if(btn){e.preventDefault();show(btn.dataset.screen)}});
$('#booking-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);const selectedDate=new Date(`${f.get('date')}T00:00:00`);if([1,2,3,4,5].includes(selectedDate.getDay())){alert('香作ワークショップは土日祝日の開催です。開催日をご確認ください。');return}const slot=slots[f.get('slot')];draft={date:f.get('date'),slot:f.get('slot'),meet:slot.meet,experience:slot.experience,guests:Number(f.get('guests')),name:f.get('name'),email:f.get('email'),age:f.get('age'),visit:f.get('visit'),source:f.get('source')||'未回答',note:f.get('note')||'未記入'};renderConfirm();show('confirm')});
function formatDate(d){if(!d)return '';const [y,m,day]=d.split('-');return `${y}年${Number(m)}月${Number(day)}日`}
function renderConfirm(){const rows=[['予約日',formatDate(draft.date)],['集合時間',draft.meet],['体験時間',draft.experience],['人数',`${draft.guests}名`],['氏名',draft.name],['年代',draft.age],['初回 / リピーター',draft.visit],['メールアドレス',draft.email],['流入元',draft.source],['備考',draft.note]];$('#confirm-content').innerHTML=`<dl>${rows.map(r=>`<div class="summary-row"><dt>${r[0]}</dt><dd>${escapeHtml(r[1])}</dd></div>`).join('')}</dl>`}
$('#confirm-button').addEventListener('click',()=>{if(!draft)return;const data=all();data.push({...draft,id:`KS-${Date.now().toString(36).toUpperCase()}`,status:'受付',createdAt:new Date().toISOString()});save(data);draft=null;$('#booking-form').reset();show('complete')});
function renderAdmin(){const data=all().sort((a,b)=>a.date.localeCompare(b.date));$('#reservation-count').textContent=`${data.length}件`;const first=data.filter(x=>x.visit==='初めて').length;const repeat=data.length-first;const total=data.reduce((n,x)=>n+Number(x.guests),0);const ages=['10代','20代','30代','40代','50代','60代以上'];const sources=['Google検索','Instagram','口コミ','店頭','知人の紹介','その他','未回答'];const bars=(arr,key)=>{const max=Math.max(1,...arr.map(v=>data.filter(x=>x[key]===v).length));return arr.map(v=>`<div class="bar-row"><span class="bar-label">${v}</span><span class="bar-track"><span class="bar-fill" style="width:${data.filter(x=>x[key]===v).length/max*100}%"></span></span><span>${data.filter(x=>x[key]===v).length}</span></div>`).join('')};$('#metrics').innerHTML=`<div class="metric"><p>総予約件数</p><strong>${data.length}</strong><small>件</small></div><div class="metric"><p>総参加人数</p><strong>${total}</strong><small>名</small></div><div class="metric"><p>初回利用者数</p><strong>${first}</strong><small>件</small></div><div class="metric"><p>リピーター数</p><strong>${repeat}</strong><small>件</small></div><div class="metric metric-wide"><p>年代別予約数</p>${bars(ages,'age')}</div><div class="metric metric-wide"><p>流入元別予約数</p>${bars(sources,'source')}</div>`;$('#reservation-list').innerHTML=data.length?data.map(item=>`<article class="reservation-item"><div class="reservation-main"><div class="reservation-date">${formatDate(item.date)}<div class="reservation-sub">${item.meet}集合</div></div><div class="reservation-name">${escapeHtml(item.name)}<div class="reservation-sub">${item.guests}名 / ${item.age} / ${item.visit} / ${item.source}</div></div><select class="status-select" data-status="${item.id}" aria-label="${escapeHtml(item.name)}さんの予約状況"><option ${item.status==='受付'?'selected':''}>受付</option><option ${item.status==='確認済み'?'selected':''}>確認済み</option><option ${item.status==='キャンセル'?'selected':''}>キャンセル</option></select></div><button class="secondary-button small" data-detail="${item.id}">詳細を見る</button></article>`).join(''):'<p class="no-data">まだ予約データがありません。</p>'}
document.addEventListener('change',e=>{if(e.target.dataset.status){const data=all();const item=data.find(x=>x.id===e.target.dataset.status);if(item){item.status=e.target.value;save(data)}}});document.addEventListener('click',e=>{const id=e.target.dataset.detail;if(id){const item=all().find(x=>x.id===id);if(item)showDetail(item)}});
function showDetail(x){const panel=$('#detail-panel');panel.hidden=false;panel.innerHTML=`<button class="detail-close" data-close-detail>閉じる</button><h2>予約詳細</h2>${[['予約ID',x.id],['予約日',formatDate(x.date)],['集合時間',x.meet],['体験時間',x.experience],['人数',`${x.guests}名`],['氏名',x.name],['メール',x.email],['年代',x.age],['来店回数',x.visit],['流入元',x.source],['備考',x.note],['作成日時',new Date(x.createdAt).toLocaleString('ja-JP')]].map(r=>`<div class="detail-row"><b>${r[0]}</b>${escapeHtml(r[1])}</div>`).join('')}`}
document.addEventListener('click',e=>{if(e.target.closest('[data-close-detail]')){const panel=$('#detail-panel');panel.hidden=true;panel.innerHTML='<p class="empty-state">一覧の「詳細を見る」から<br>予約内容を確認できます。</p>'}});
function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
// 過去日を選べないようにし、画面初期表示時に管理画面も復元できるようにする
$('#date').min=new Date().toISOString().slice(0,10);
